version: "2.4"

services:
  database-postgresql:
    extends:
      file: containers/postgresql.yaml
      service: database-postgresql
    container_name: database-postgresql
  redis-server:
    extends:
      file: containers/redis.yaml
      service: redis-server
    container_name: redis-server
