networks:
  fmf-algafood-network:
    driver: bridge

services:
  database-postgresql:
    extends:
      file: containers/postgresql.yaml
      service: database-postgresql
    networks:
      - fmf-algafood-network

  fmf-algafood-api:
    extends:
      file: containers/service-api.yaml
      service: fmf-algafood-api
    networks:
      - fmf-algafood-network
    depends_on:
      - database-postgresql

  fmf-algafood-proxy:
    extends:
      file: containers/proxy.yaml
      service: fmf-algafood-proxy
    networks:
      - fmf-algafood-network
    depends_on:
      - fmf-algafood-api
